; bed.g
; called to perform automatic bed compensation via G32
;
; generated by RepRapFirmware Configuration Tool v3.3.10 on Fri Mar 25 2022 03:37:45 GMT+0100 (Central European Standard Time)

M561 ; clear any bed transform

G30 P0 Y72.5 X15 Z-99999
G30 P1 Y72.5 X120 Z-99999 S2

G28 Z
