; homez.g
; called to home the Z axis
;
; generated by RepRapFirmware Configuration Tool v3.3.10 on Fri Mar 25 2022 03:37:45 GMT+0100 (Central European Standard Time)

G91                ; relative positioning
G1 H2 Z5 F1500     ; lift Z relative to current position
G90                ; absolute positioning
G1 X88.244 Y91.75 F1500   ; go to bed center, minus probe offset
G30                ; probe the bed using z probe to find Z0
